name: Send Change Package on Change

on:
  push:
    branches: [ "main" ]
    paths:
      - 'laal-saas/**'
jobs:
  detect-directory-changes:
    name: "Detect Directory Changes"
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.detect.outputs.changed }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Detect Directory Changes
        id: detect
        uses: tchupp/actions-detect-directory-changes@v1
  create-change-package:
    needs: detect-directory-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.detect-directory-changes.outputs.changed) }}
    steps:
    - name: Dir name
      id: dir-name
      run: echo "dir=$(echo ${{ matrix.dir }} | cut --complement -f1 -d\/)" >> "$GITHUB_OUTPUT"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Zip file
      run: | 
        echo ${{ steps.dir-name.outputs.dir }}
        cd ${{ vars.REPO_PATH_LAALSAAS }}
        ls
        zip -r ${{ steps.dir-name.outputs.dir }}.zip ${{ steps.dir-name.outputs.dir }}
    - uses: actions/upload-artifact@v3
      with:
        path: ${{ vars.REPO_PATH_LAALSAAS }}${{ steps.dir-name.outputs.dir }}.zip
        name: ${{ steps.dir-name.outputs.dir }}
  send-file-via-sftp:
    needs: [detect-directory-changes, create-change-package]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: ${{ fromJson(needs.detect-directory-changes.outputs.changed) }}
    steps:
    - name: Dir name
      id: dir-name
      run: echo "dir=$(echo ${{ matrix.dir }} | cut --complement -f1 -d\/)" >> "$GITHUB_OUTPUT"
    - uses: actions/download-artifact@v3
      id: download
      with:
        path: ${{ steps.dir-name.outputs.dir }}.zip
        name: ${{ steps.dir-name.outputs.dir }}
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ${{ secrets.REMOTE_HOST_TAZU }}
        privateKey: ${{ secrets.KEY_TAZU }} 
        localDir: ${{ steps.download.outputs.download-path }}
        remoteDir: ${{ vars.SFTP_PATH_TAZU }}
        dryRun: false
        username: ${{ secrets.USERNAME_TAZU }} 

